replicaCount: 1
image:
  repository: ems/backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
