apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow
  namespace: ems
spec:
  podSelector:
    matchLabels:
      app: ems-backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - port: 8000
