apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-allow
  namespace: ems
spec:
  podSelector:
    matchLabels:
      app: postgresql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ems-backend
      ports:
        - port: 5432
