apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kong.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kong.name" . }}
    spec:
      containers:
        - name: kong
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
