apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: ems-daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - ems
    storageLocation: default
    ttl: 720h
